FROM node:20 AS build

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm -F @monorepo/server run build

RUN rm -rf app/apps/ui

# ----------------------------

FROM node:20 AS release

WORKDIR /app

COPY --from=build /app .

EXPOSE 3001

CMD [ "node", "apps/server/dist/app.js" ]