FROM node:20 AS build

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm -F @monorepo/ui run build

RUN rm -rf app/apps/server

# ----------------------------

FROM nginx:alpine3.18 AS release

WORKDIR /app

COPY --from=build /app .

COPY apps/ui/dist /usr/share/nginx/html

EXPOSE 80