FROM node:20 AS build

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm -F @monorepo/server run build

# ----------------------------

FROM node:20 AS release

WORKDIR /app

COPY --from=build /app/apps/server/dist .

CMD [ "node", "app.js" ]