FROM node:20 AS build

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm -F @monorepo/ui run build

RUN rm -rf apps/server

# ----------------------------

FROM nginx:alpine3.18

WORKDIR /app

COPY --from=build /app .

COPY /app/apps/ui/dist /usr/share/nginx/html

EXPOSE 80